### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by ChrisChinchilla** [sorbetto/sorbetto#5]
I was thinking the other day of starting a Swift static site generator and just came across your repo via IBM, need help with this?

**Comment by DanToml** [comment]
@ChrisChinchilla Hey Chris, I've been pretty swamped lately and would love an extra hand!
Something I've been meaning to do is build a couple of plugins that are required for Sorbetto to be useful (mostly Markdown parsing). I think this would require moving protocols/base types into Sorbetto/Core. If you'd like to take a stab at that, it would be very much appreciated!

I'll convert the rest of my initial release todo list into issues tonight, and I welcome any ideas you might have around API and usage!

**Comment by ChrisChinchilla** [comment]
@DanToml OK, I may need a few weeks to find time, but I will take a look asap. :)
